// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bram_xike,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325tffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.410000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=10,HLS_SYN_LUT=204}" *)

module bram_xike (
        ap_clk,
        ap_rst,
        p_doWrite,
        din,
        p_doRead,
        dout,
        dout_ap_vld,
        p_addr_V,
        p_scale_read,
        p_scale_addr_V,
        scale_out,
        scale_out_ap_vld,
        p_shift_read,
        p_shift_addr_V,
        shift_out,
        shift_out_ap_vld,
        p_pca_read,
        p_pca_addr_V,
        pca_out,
        pca_out_ap_vld,
        p_vq_read,
        p_vq_addr_V,
        vq_out,
        vq_out_ap_vld
);

parameter    ap_ST_pp0_stg0_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv16_28 = 16'b101000;
parameter    ap_const_lv16_A0 = 16'b10100000;
parameter    ap_const_lv16_C80 = 16'b110010000000;
parameter    ap_const_lv17_1F380 = 17'b11111001110000000;
parameter    ap_const_lv17_1FF60 = 17'b11111111101100000;
parameter    ap_const_lv17_1FFD8 = 17'b11111111111011000;

input   ap_clk;
input   ap_rst;
input   p_doWrite;
input  [31:0] din;
input   p_doRead;
output  [31:0] dout;
output   dout_ap_vld;
input  [15:0] p_addr_V;
input   p_scale_read;
input  [7:0] p_scale_addr_V;
output  [31:0] scale_out;
output   scale_out_ap_vld;
input   p_shift_read;
input  [7:0] p_shift_addr_V;
output  [31:0] shift_out;
output   shift_out_ap_vld;
input   p_pca_read;
input  [15:0] p_pca_addr_V;
output  [31:0] pca_out;
output   pca_out_ap_vld;
input   p_vq_read;
input  [15:0] p_vq_addr_V;
output  [31:0] vq_out;
output   vq_out_ap_vld;

reg[31:0] dout;
reg dout_ap_vld;
reg scale_out_ap_vld;
reg shift_out_ap_vld;
reg pca_out_ap_vld;
reg vq_out_ap_vld;

wire   [5:0] scale_address0;
reg    scale_ce0;
wire   [31:0] scale_q0;
reg   [5:0] scale_address1;
reg    scale_ce1;
reg    scale_we1;
wire   [31:0] scale_q1;
wire   [6:0] shift_address0;
reg    shift_ce0;
wire   [31:0] shift_q0;
reg   [6:0] shift_address1;
reg    shift_ce1;
reg    shift_we1;
wire   [31:0] shift_q1;
wire   [11:0] pca_address0;
reg    pca_ce0;
wire   [31:0] pca_q0;
reg   [11:0] pca_address1;
reg    pca_ce1;
reg    pca_we1;
wire   [31:0] pca_q1;
wire   [11:0] vq_address0;
reg    vq_ce0;
wire   [31:0] vq_q0;
reg   [11:0] vq_address1;
reg    vq_ce1;
reg    vq_we1;
wire   [31:0] vq_q1;
reg   [0:0] p_vq_read_read_reg_523;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_91;
reg    ap_reg_ppiten_pp0_it1;
reg   [0:0] p_pca_read_read_reg_527;
reg   [0:0] p_shift_read_read_reg_531;
reg   [0:0] p_scale_read_read_reg_535;
wire   [0:0] p_doRead_read_read_fu_158_p2;
reg   [0:0] p_doRead_read_reg_539;
wire   [0:0] p_doWrite_read_read_fu_170_p2;
reg   [0:0] p_doWrite_read_reg_543;
wire   [1:0] mem_state_3_fu_415_p3;
reg   [1:0] mem_state_3_reg_567;
wire   [63:0] tmp_6_fu_347_p1;
wire   [63:0] tmp_7_fu_352_p1;
wire   [63:0] tmp_8_fu_357_p1;
wire   [63:0] tmp_9_fu_362_p1;
wire  signed [63:0] tmp_14_fu_433_p1;
wire  signed [63:0] tmp_13_fu_448_p1;
wire  signed [63:0] tmp_12_fu_463_p1;
wire   [63:0] tmp_11_fu_468_p1;
wire  signed [63:0] tmp_10_fu_483_p1;
wire  signed [63:0] tmp_5_fu_498_p1;
wire  signed [63:0] tmp_3_fu_513_p1;
wire   [63:0] tmp_1_fu_518_p1;
wire   [0:0] tmp_4_fu_379_p2;
wire   [0:0] tmp_s_fu_367_p2;
wire   [0:0] tmp_2_fu_373_p2;
wire   [0:0] sel_tmp1_fu_393_p2;
wire   [0:0] sel_tmp2_fu_399_p2;
wire   [0:0] tmp_fu_409_p2;
wire   [1:0] sel_tmp_fu_405_p1;
wire   [1:0] p_s_fu_385_p3;
wire   [16:0] lhs_V_5_cast_fu_423_p1;
wire   [16:0] r_V_5_fu_427_p2;
wire   [16:0] lhs_V_4_cast_fu_438_p1;
wire   [16:0] r_V_4_fu_442_p2;
wire   [16:0] lhs_V_3_cast_fu_453_p1;
wire   [16:0] r_V_3_fu_457_p2;
wire   [16:0] lhs_V_2_cast_fu_473_p1;
wire   [16:0] r_V_2_fu_477_p2;
wire   [16:0] lhs_V_1_cast_fu_488_p1;
wire   [16:0] r_V_1_fu_492_p2;
wire   [16:0] lhs_V_cast_fu_503_p1;
wire   [16:0] r_V_fu_507_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_sig_pprstidle_pp0;
reg    ap_sig_363;
reg    ap_sig_136;
reg    ap_sig_365;
reg    ap_sig_368;
reg    ap_sig_370;
reg    ap_sig_372;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
end

bram_xike_scale #(
    .DataWidth( 32 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(scale_address0),
    .ce0(scale_ce0),
    .q0(scale_q0),
    .address1(scale_address1),
    .ce1(scale_ce1),
    .we1(scale_we1),
    .d1(din),
    .q1(scale_q1)
);

bram_xike_shift #(
    .DataWidth( 32 ),
    .AddressRange( 120 ),
    .AddressWidth( 7 ))
shift_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(shift_address0),
    .ce0(shift_ce0),
    .q0(shift_q0),
    .address1(shift_address1),
    .ce1(shift_ce1),
    .we1(shift_we1),
    .d1(din),
    .q1(shift_q1)
);

bram_xike_pca #(
    .DataWidth( 32 ),
    .AddressRange( 3040 ),
    .AddressWidth( 12 ))
pca_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pca_address0),
    .ce0(pca_ce0),
    .q0(pca_q0),
    .address1(pca_address1),
    .ce1(pca_ce1),
    .we1(pca_we1),
    .d1(din),
    .q1(pca_q1)
);

bram_xike_vq #(
    .DataWidth( 32 ),
    .AddressRange( 4000 ),
    .AddressWidth( 12 ))
vq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(vq_address0),
    .ce0(vq_ce0),
    .q0(vq_q0),
    .address1(vq_address1),
    .ce1(vq_ce1),
    .we1(vq_we1),
    .d1(din),
    .q1(vq_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
        mem_state_3_reg_567 <= mem_state_3_fu_415_p3;
        p_doRead_read_reg_539 <= p_doRead;
        p_doWrite_read_reg_543 <= p_doWrite;
        p_pca_read_read_reg_527 <= p_pca_read;
        p_scale_read_read_reg_535 <= p_scale_read;
        p_shift_read_read_reg_531 <= p_shift_read;
        p_vq_read_read_reg_523 <= p_vq_read;
    end
end

always @ (*) begin
    if (ap_sig_91) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b0;
    end
end

assign ap_sig_pprstidle_pp0 = 1'b0;

always @ (*) begin
    if (ap_sig_363) begin
        if ((mem_state_3_reg_567 == ap_const_lv2_0)) begin
            dout = scale_q1;
        end else if ((mem_state_3_reg_567 == ap_const_lv2_1)) begin
            dout = shift_q1;
        end else if ((mem_state_3_reg_567 == ap_const_lv2_2)) begin
            dout = pca_q1;
        end else if ((mem_state_3_reg_567 == ap_const_lv2_3)) begin
            dout = vq_q1;
        end else begin
            dout = 'bx;
        end
    end else begin
        dout = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & (p_doWrite_read_reg_543 == 1'b0) & ~(p_doRead_read_reg_539 == 1'b0) & (mem_state_3_reg_567 == ap_const_lv2_3)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & (p_doWrite_read_reg_543 == 1'b0) & ~(p_doRead_read_reg_539 == 1'b0) & (mem_state_3_reg_567 == ap_const_lv2_2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & (p_doWrite_read_reg_543 == 1'b0) & ~(p_doRead_read_reg_539 == 1'b0) & (mem_state_3_reg_567 == ap_const_lv2_1)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & (p_doWrite_read_reg_543 == 1'b0) & ~(p_doRead_read_reg_539 == 1'b0) & (mem_state_3_reg_567 == ap_const_lv2_0)))) begin
        dout_ap_vld = 1'b1;
    end else begin
        dout_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_365) begin
        if (~(p_doWrite_read_read_fu_170_p2 == 1'b0)) begin
            pca_address1 = tmp_5_fu_498_p1;
        end else if (ap_sig_136) begin
            pca_address1 = tmp_13_fu_448_p1;
        end else begin
            pca_address1 = 'bx;
        end
    end else begin
        pca_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1))) begin
        pca_ce0 = 1'b1;
    end else begin
        pca_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (p_doWrite_read_read_fu_170_p2 == 1'b0) & ~(p_doRead_read_read_fu_158_p2 == 1'b0) & (mem_state_3_fu_415_p3 == ap_const_lv2_2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_2) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0)))) begin
        pca_ce1 = 1'b1;
    end else begin
        pca_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(p_pca_read_read_reg_527 == 1'b0))) begin
        pca_out_ap_vld = 1'b1;
    end else begin
        pca_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_2) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0))) begin
        pca_we1 = 1'b1;
    end else begin
        pca_we1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_368) begin
        if (~(p_doWrite_read_read_fu_170_p2 == 1'b0)) begin
            scale_address1 = tmp_1_fu_518_p1;
        end else if (ap_sig_136) begin
            scale_address1 = tmp_11_fu_468_p1;
        end else begin
            scale_address1 = 'bx;
        end
    end else begin
        scale_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1))) begin
        scale_ce0 = 1'b1;
    end else begin
        scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (p_doWrite_read_read_fu_170_p2 == 1'b0) & ~(p_doRead_read_read_fu_158_p2 == 1'b0) & (mem_state_3_fu_415_p3 == ap_const_lv2_0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_0) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0)))) begin
        scale_ce1 = 1'b1;
    end else begin
        scale_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(p_scale_read_read_reg_535 == 1'b0))) begin
        scale_out_ap_vld = 1'b1;
    end else begin
        scale_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_0) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0))) begin
        scale_we1 = 1'b1;
    end else begin
        scale_we1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_370) begin
        if (~(p_doWrite_read_read_fu_170_p2 == 1'b0)) begin
            shift_address1 = tmp_3_fu_513_p1;
        end else if (ap_sig_136) begin
            shift_address1 = tmp_12_fu_463_p1;
        end else begin
            shift_address1 = 'bx;
        end
    end else begin
        shift_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1))) begin
        shift_ce0 = 1'b1;
    end else begin
        shift_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (p_doWrite_read_read_fu_170_p2 == 1'b0) & ~(p_doRead_read_read_fu_158_p2 == 1'b0) & (mem_state_3_fu_415_p3 == ap_const_lv2_1)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_1) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0)))) begin
        shift_ce1 = 1'b1;
    end else begin
        shift_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(p_shift_read_read_reg_531 == 1'b0))) begin
        shift_out_ap_vld = 1'b1;
    end else begin
        shift_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_1) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0))) begin
        shift_we1 = 1'b1;
    end else begin
        shift_we1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_372) begin
        if (~(p_doWrite_read_read_fu_170_p2 == 1'b0)) begin
            vq_address1 = tmp_10_fu_483_p1;
        end else if (ap_sig_136) begin
            vq_address1 = tmp_14_fu_433_p1;
        end else begin
            vq_address1 = 'bx;
        end
    end else begin
        vq_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1))) begin
        vq_ce0 = 1'b1;
    end else begin
        vq_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (p_doWrite_read_read_fu_170_p2 == 1'b0) & ~(p_doRead_read_read_fu_158_p2 == 1'b0) & (mem_state_3_fu_415_p3 == ap_const_lv2_3)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_3) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0)))) begin
        vq_ce1 = 1'b1;
    end else begin
        vq_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(p_vq_read_read_reg_523 == 1'b0))) begin
        vq_out_ap_vld = 1'b1;
    end else begin
        vq_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_3) & ~(p_doWrite_read_read_fu_170_p2 == 1'b0))) begin
        vq_we1 = 1'b1;
    end else begin
        vq_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_136 = ((p_doWrite_read_read_fu_170_p2 == 1'b0) & ~(p_doRead_read_read_fu_158_p2 == 1'b0));
end

always @ (*) begin
    ap_sig_363 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & (p_doWrite_read_reg_543 == 1'b0) & ~(p_doRead_read_reg_539 == 1'b0));
end

always @ (*) begin
    ap_sig_365 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_2));
end

always @ (*) begin
    ap_sig_368 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_0));
end

always @ (*) begin
    ap_sig_370 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_1));
end

always @ (*) begin
    ap_sig_372 = ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == 1'b1) & (mem_state_3_fu_415_p3 == ap_const_lv2_3));
end

always @ (*) begin
    ap_sig_91 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

assign lhs_V_1_cast_fu_488_p1 = p_addr_V;

assign lhs_V_2_cast_fu_473_p1 = p_addr_V;

assign lhs_V_3_cast_fu_453_p1 = p_addr_V;

assign lhs_V_4_cast_fu_438_p1 = p_addr_V;

assign lhs_V_5_cast_fu_423_p1 = p_addr_V;

assign lhs_V_cast_fu_503_p1 = p_addr_V;

assign mem_state_3_fu_415_p3 = ((tmp_fu_409_p2[0:0] === 1'b1) ? sel_tmp_fu_405_p1 : p_s_fu_385_p3);

assign p_doRead_read_read_fu_158_p2 = p_doRead;

assign p_doWrite_read_read_fu_170_p2 = p_doWrite;

assign p_s_fu_385_p3 = ((tmp_4_fu_379_p2[0:0] === 1'b1) ? ap_const_lv2_2 : ap_const_lv2_3);

assign pca_address0 = tmp_8_fu_357_p1;

assign pca_out = pca_q0;

assign r_V_1_fu_492_p2 = ($signed(lhs_V_1_cast_fu_488_p1) + $signed(ap_const_lv17_1FF60));

assign r_V_2_fu_477_p2 = ($signed(lhs_V_2_cast_fu_473_p1) + $signed(ap_const_lv17_1F380));

assign r_V_3_fu_457_p2 = ($signed(lhs_V_3_cast_fu_453_p1) + $signed(ap_const_lv17_1FFD8));

assign r_V_4_fu_442_p2 = ($signed(lhs_V_4_cast_fu_438_p1) + $signed(ap_const_lv17_1FF60));

assign r_V_5_fu_427_p2 = ($signed(lhs_V_5_cast_fu_423_p1) + $signed(ap_const_lv17_1F380));

assign r_V_fu_507_p2 = ($signed(lhs_V_cast_fu_503_p1) + $signed(ap_const_lv17_1FFD8));

assign scale_address0 = tmp_6_fu_347_p1;

assign scale_out = scale_q0;

assign sel_tmp1_fu_393_p2 = (tmp_s_fu_367_p2 ^ 1'b1);

assign sel_tmp2_fu_399_p2 = (tmp_2_fu_373_p2 & sel_tmp1_fu_393_p2);

assign sel_tmp_fu_405_p1 = sel_tmp2_fu_399_p2;

assign shift_address0 = tmp_7_fu_352_p1;

assign shift_out = shift_q0;

assign tmp_10_fu_483_p1 = $signed(r_V_2_fu_477_p2);

assign tmp_11_fu_468_p1 = p_addr_V;

assign tmp_12_fu_463_p1 = $signed(r_V_3_fu_457_p2);

assign tmp_13_fu_448_p1 = $signed(r_V_4_fu_442_p2);

assign tmp_14_fu_433_p1 = $signed(r_V_5_fu_427_p2);

assign tmp_1_fu_518_p1 = p_addr_V;

assign tmp_2_fu_373_p2 = ((p_addr_V < ap_const_lv16_A0) ? 1'b1 : 1'b0);

assign tmp_3_fu_513_p1 = $signed(r_V_fu_507_p2);

assign tmp_4_fu_379_p2 = ((p_addr_V < ap_const_lv16_C80) ? 1'b1 : 1'b0);

assign tmp_5_fu_498_p1 = $signed(r_V_1_fu_492_p2);

assign tmp_6_fu_347_p1 = p_scale_addr_V;

assign tmp_7_fu_352_p1 = p_shift_addr_V;

assign tmp_8_fu_357_p1 = p_pca_addr_V;

assign tmp_9_fu_362_p1 = p_vq_addr_V;

assign tmp_fu_409_p2 = (sel_tmp2_fu_399_p2 | tmp_s_fu_367_p2);

assign tmp_s_fu_367_p2 = ((p_addr_V < ap_const_lv16_28) ? 1'b1 : 1'b0);

assign vq_address0 = tmp_9_fu_362_p1;

assign vq_out = vq_q0;

endmodule //bram_xike
