// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="spk_packet_rx,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325tffg900-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.410000,HLS_SYN_LAT=11,HLS_SYN_TPT=none,HLS_SYN_MEM=60,HLS_SYN_DSP=2,HLS_SYN_FF=1082,HLS_SYN_LUT=910}" *)

module spk_packet_rx (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pre_in_TUSER,
        pre_in_TVALID,
        pre_in_TREADY,
        pre_in_TLAST,
        pre_in_TID,
        pre_in_TDATA,
        pre_in_TDEST,
        post_in_TUSER,
        post_in_TVALID,
        post_in_TREADY,
        post_in_TLAST,
        post_in_TID,
        post_in_TDATA,
        post_in_TDEST,
        time_stamp_V_TDATA,
        time_stamp_V_TVALID,
        time_stamp_V_TREADY,
        spk_out_stream_V_data_V_TDATA,
        spk_out_stream_V_data_V_TVALID,
        spk_out_stream_V_data_V_TREADY
);

parameter    ap_ST_st1_fsm_0 = 16'b1;
parameter    ap_ST_st2_fsm_1 = 16'b10;
parameter    ap_ST_st3_fsm_2 = 16'b100;
parameter    ap_ST_st4_fsm_3 = 16'b1000;
parameter    ap_ST_st5_fsm_4 = 16'b10000;
parameter    ap_ST_st6_fsm_5 = 16'b100000;
parameter    ap_ST_st7_fsm_6 = 16'b1000000;
parameter    ap_ST_st8_fsm_7 = 16'b10000000;
parameter    ap_ST_st9_fsm_8 = 16'b100000000;
parameter    ap_ST_st10_fsm_9 = 16'b1000000000;
parameter    ap_ST_st11_fsm_10 = 16'b10000000000;
parameter    ap_ST_st12_fsm_11 = 16'b100000000000;
parameter    ap_ST_st13_fsm_12 = 16'b1000000000000;
parameter    ap_ST_pp0_stg0_fsm_13 = 16'b10000000000000;
parameter    ap_ST_pp1_stg0_fsm_14 = 16'b100000000000000;
parameter    ap_ST_st20_fsm_15 = 16'b1000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv13_13 = 13'b10011;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv29_0 = 29'b00000000000000000000000000000;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv5_12 = 5'b10010;
parameter    ap_const_lv32_F = 32'b1111;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] pre_in_TUSER;
input   pre_in_TVALID;
output   pre_in_TREADY;
input   pre_in_TLAST;
input  [11:0] pre_in_TID;
input  [127:0] pre_in_TDATA;
input  [0:0] pre_in_TDEST;
input  [4:0] post_in_TUSER;
input   post_in_TVALID;
output   post_in_TREADY;
input   post_in_TLAST;
input  [11:0] post_in_TID;
input  [127:0] post_in_TDATA;
input  [0:0] post_in_TDEST;
input  [31:0] time_stamp_V_TDATA;
input   time_stamp_V_TVALID;
output   time_stamp_V_TREADY;
output  [127:0] spk_out_stream_V_data_V_TDATA;
output   spk_out_stream_V_data_V_TVALID;
input   spk_out_stream_V_data_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_33;
reg   [4:0] pre_in_V_user_V_0_data_out;
wire    pre_in_V_user_V_0_vld_in;
wire    pre_in_V_user_V_0_vld_out;
reg    pre_in_V_user_V_0_ack_out;
reg   [4:0] pre_in_V_user_V_0_data_reg;
reg    pre_in_V_user_V_0_areset_d;
reg    pre_in_V_user_V_0_in_rdy;
reg    pre_in_V_user_V_0_has_vld_data_reg_i;
reg    pre_in_V_user_V_0_has_vld_data_reg;
wire    pre_in_V_last_0_vld_in;
wire    pre_in_V_last_0_vld_out;
reg    pre_in_V_last_0_ack_out;
reg    pre_in_V_last_0_areset_d;
reg    pre_in_V_last_0_in_rdy;
reg    pre_in_V_last_0_has_vld_data_reg_i;
reg    pre_in_V_last_0_has_vld_data_reg;
reg   [11:0] pre_in_V_id_V_0_data_out;
wire    pre_in_V_id_V_0_vld_in;
wire    pre_in_V_id_V_0_vld_out;
reg    pre_in_V_id_V_0_ack_out;
reg   [11:0] pre_in_V_id_V_0_data_reg;
reg    pre_in_V_id_V_0_areset_d;
reg    pre_in_V_id_V_0_in_rdy;
reg    pre_in_V_id_V_0_has_vld_data_reg_i;
reg    pre_in_V_id_V_0_has_vld_data_reg;
reg   [127:0] pre_in_V_data_V_0_data_out;
wire    pre_in_V_data_V_0_vld_in;
wire    pre_in_V_data_V_0_vld_out;
reg    pre_in_V_data_V_0_ack_out;
reg   [127:0] pre_in_V_data_V_0_data_reg;
reg    pre_in_V_data_V_0_areset_d;
reg    pre_in_V_data_V_0_in_rdy;
reg    pre_in_V_data_V_0_has_vld_data_reg_i;
reg    pre_in_V_data_V_0_has_vld_data_reg;
reg   [0:0] pre_in_V_dest_V_0_data_out;
wire    pre_in_V_dest_V_0_vld_in;
wire    pre_in_V_dest_V_0_vld_out;
reg    pre_in_V_dest_V_0_ack_out;
reg   [0:0] pre_in_V_dest_V_0_data_reg;
reg    pre_in_V_dest_V_0_areset_d;
reg    pre_in_V_dest_V_0_in_rdy;
reg    pre_in_V_dest_V_0_has_vld_data_reg_i;
reg    pre_in_V_dest_V_0_has_vld_data_reg;
reg   [4:0] post_in_V_user_V_0_data_out;
wire    post_in_V_user_V_0_vld_in;
wire    post_in_V_user_V_0_vld_out;
reg    post_in_V_user_V_0_ack_out;
reg   [4:0] post_in_V_user_V_0_data_reg;
reg    post_in_V_user_V_0_areset_d;
reg    post_in_V_user_V_0_in_rdy;
reg    post_in_V_user_V_0_has_vld_data_reg_i;
reg    post_in_V_user_V_0_has_vld_data_reg;
reg    post_in_V_last_0_data_out;
wire    post_in_V_last_0_vld_in;
wire    post_in_V_last_0_vld_out;
reg    post_in_V_last_0_ack_out;
reg    post_in_V_last_0_data_reg;
reg    post_in_V_last_0_areset_d;
reg    post_in_V_last_0_in_rdy;
reg    post_in_V_last_0_has_vld_data_reg_i;
reg    post_in_V_last_0_has_vld_data_reg;
reg   [11:0] post_in_V_id_V_0_data_out;
wire    post_in_V_id_V_0_vld_in;
wire    post_in_V_id_V_0_vld_out;
reg    post_in_V_id_V_0_ack_out;
reg   [11:0] post_in_V_id_V_0_data_reg;
reg    post_in_V_id_V_0_areset_d;
reg    post_in_V_id_V_0_in_rdy;
reg    post_in_V_id_V_0_has_vld_data_reg_i;
reg    post_in_V_id_V_0_has_vld_data_reg;
reg   [127:0] post_in_V_data_V_0_data_out;
wire    post_in_V_data_V_0_vld_in;
wire    post_in_V_data_V_0_vld_out;
reg    post_in_V_data_V_0_ack_out;
reg   [127:0] post_in_V_data_V_0_data_reg;
reg    post_in_V_data_V_0_areset_d;
reg    post_in_V_data_V_0_in_rdy;
reg    post_in_V_data_V_0_has_vld_data_reg_i;
reg    post_in_V_data_V_0_has_vld_data_reg;
reg   [0:0] post_in_V_dest_V_0_data_out;
wire    post_in_V_dest_V_0_vld_in;
wire    post_in_V_dest_V_0_vld_out;
reg    post_in_V_dest_V_0_ack_out;
reg   [0:0] post_in_V_dest_V_0_data_reg;
reg    post_in_V_dest_V_0_areset_d;
reg    post_in_V_dest_V_0_in_rdy;
reg    post_in_V_dest_V_0_has_vld_data_reg_i;
reg    post_in_V_dest_V_0_has_vld_data_reg;
reg   [31:0] time_stamp_V_0_data_out;
wire    time_stamp_V_0_vld_in;
wire    time_stamp_V_0_vld_out;
reg    time_stamp_V_0_ack_out;
reg   [31:0] time_stamp_V_0_data_reg;
reg    time_stamp_V_0_areset_d;
reg    time_stamp_V_0_in_rdy;
reg    time_stamp_V_0_has_vld_data_reg_i;
reg    time_stamp_V_0_has_vld_data_reg;
reg   [127:0] spk_out_stream_V_data_V_1_data_in;
reg    spk_out_stream_V_data_V_1_vld_in;
reg    spk_out_stream_V_data_V_1_ack_in;
wire    spk_out_stream_V_data_V_1_ack_out;
reg   [127:0] spk_out_stream_V_data_V_1_data_reg;
reg    spk_out_stream_V_data_V_1_sRdy;
reg    spk_out_stream_V_data_V_1_mVld;
reg    spk_out_stream_V_data_V_1_areset_d;
reg   [11:0] spk_A_V_address0;
reg    spk_A_V_ce0;
reg    spk_A_V_we0;
reg   [127:0] spk_A_V_d0;
wire   [127:0] spk_A_V_q0;
reg   [11:0] spk_B_V_address0;
reg    spk_B_V_ce0;
reg    spk_B_V_we0;
reg   [127:0] spk_B_V_d0;
wire   [127:0] spk_B_V_q0;
reg    pre_in_TDATA_blk_n;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_446;
wire   [0:0] grp_nbreadreq_fu_90_p7;
reg    post_in_TDATA_blk_n;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_459;
wire   [0:0] grp_nbreadreq_fu_120_p7;
reg    time_stamp_V_TDATA_blk_n;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_471;
reg    spk_out_stream_V_data_V_TDATA_blk_n;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_483;
wire   [0:0] icmp_fu_322_p2;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_494;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_13;
reg    ap_sig_502;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_14;
reg    ap_sig_518;
reg    ap_reg_ppiten_pp1_it1;
reg    ap_reg_ppiten_pp1_it0;
reg    ap_reg_ppiten_pp1_it2;
reg   [4:0] j3_reg_221;
reg   [4:0] j_reg_232;
reg   [0:0] tmp_reg_403;
reg    ap_sig_536;
reg   [4:0] empty_reg_407_0;
reg   [11:0] empty_reg_407_2;
reg   [127:0] empty_reg_407_3;
reg   [0:0] empty_reg_407_4;
reg   [4:0] tmp_user_V_reg_415;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_559;
reg   [127:0] tmp_data_V_reg_420;
reg   [0:0] tmp_dest_V_reg_426;
wire  signed [63:0] tmp_5_cast_fu_262_p1;
reg  signed [63:0] tmp_5_cast_reg_435;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_574;
reg    ap_sig_579;
reg   [4:0] empty_4_reg_445_0;
reg   [0:0] empty_4_reg_445_1;
reg   [11:0] empty_4_reg_445_2;
reg   [127:0] empty_4_reg_445_3;
reg   [0:0] empty_4_reg_445_4;
reg   [11:0] tmp_id_V_1_reg_454;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_602;
wire   [12:0] grp_fu_272_p2;
reg   [12:0] tmp_6_reg_464;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_613;
reg    ap_sig_618;
wire   [0:0] tmp_dest_V_1_fu_289_p1;
reg   [0:0] tmp_dest_V_1_reg_475;
reg   [31:0] tmp_2_reg_479;
wire   [127:0] tmp_data_V_5_fu_331_p4;
wire   [4:0] j_2_fu_356_p2;
reg   [4:0] j_2_reg_498;
wire   [0:0] exitcond1_fu_362_p2;
reg   [0:0] exitcond1_reg_503;
wire   [4:0] j_1_fu_382_p2;
reg   [4:0] j_1_reg_517;
wire   [0:0] exitcond_fu_388_p2;
reg   [0:0] exitcond_reg_522;
reg   [4:0] j3_phi_fu_225_p4;
reg   [4:0] j_phi_fu_236_p4;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_695;
wire  signed [63:0] tmp_12_cast_fu_301_p1;
wire  signed [63:0] tmp_16_cast_fu_351_p1;
wire  signed [63:0] tmp_14_cast_fu_377_p1;
wire   [12:0] grp_fu_394_p3;
wire   [11:0] grp_fu_272_p0;
wire   [5:0] grp_fu_272_p1;
wire   [12:0] tmp_8_cast_fu_292_p1;
wire   [12:0] tmp_s_fu_296_p2;
wire   [31:0] t_fu_307_p2;
wire   [28:0] tmp_3_fu_312_p4;
wire   [31:0] loc_V_5_trunc_fu_328_p1;
wire   [12:0] tmp_13_cast_fu_342_p1;
wire   [12:0] tmp_10_fu_346_p2;
wire   [12:0] tmp_11_cast_fu_368_p1;
wire   [12:0] tmp_8_fu_372_p2;
wire   [11:0] grp_fu_394_p0;
wire   [5:0] grp_fu_394_p1;
wire   [4:0] grp_fu_394_p2;
reg    ap_sig_cseq_ST_st20_fsm_15;
reg    ap_sig_900;
reg   [15:0] ap_NS_fsm;
wire   [12:0] grp_fu_272_p00;
wire   [12:0] grp_fu_394_p00;
wire   [12:0] grp_fu_394_p20;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'b1;
#0 pre_in_V_user_V_0_in_rdy = 1'b0;
#0 pre_in_V_user_V_0_has_vld_data_reg = 1'b0;
#0 pre_in_V_last_0_in_rdy = 1'b0;
#0 pre_in_V_last_0_has_vld_data_reg = 1'b0;
#0 pre_in_V_id_V_0_in_rdy = 1'b0;
#0 pre_in_V_id_V_0_has_vld_data_reg = 1'b0;
#0 pre_in_V_data_V_0_in_rdy = 1'b0;
#0 pre_in_V_data_V_0_has_vld_data_reg = 1'b0;
#0 pre_in_V_dest_V_0_in_rdy = 1'b0;
#0 pre_in_V_dest_V_0_has_vld_data_reg = 1'b0;
#0 post_in_V_user_V_0_in_rdy = 1'b0;
#0 post_in_V_user_V_0_has_vld_data_reg = 1'b0;
#0 post_in_V_last_0_in_rdy = 1'b0;
#0 post_in_V_last_0_has_vld_data_reg = 1'b0;
#0 post_in_V_id_V_0_in_rdy = 1'b0;
#0 post_in_V_id_V_0_has_vld_data_reg = 1'b0;
#0 post_in_V_data_V_0_in_rdy = 1'b0;
#0 post_in_V_data_V_0_has_vld_data_reg = 1'b0;
#0 post_in_V_dest_V_0_in_rdy = 1'b0;
#0 post_in_V_dest_V_0_has_vld_data_reg = 1'b0;
#0 time_stamp_V_0_in_rdy = 1'b0;
#0 time_stamp_V_0_has_vld_data_reg = 1'b0;
#0 spk_out_stream_V_data_V_1_mVld = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp1_it1 = 1'b0;
#0 ap_reg_ppiten_pp1_it0 = 1'b0;
#0 ap_reg_ppiten_pp1_it2 = 1'b0;
end

spk_packet_rx_spk_A_V #(
    .DataWidth( 128 ),
    .AddressRange( 3040 ),
    .AddressWidth( 12 ))
spk_A_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(spk_A_V_address0),
    .ce0(spk_A_V_ce0),
    .we0(spk_A_V_we0),
    .d0(spk_A_V_d0),
    .q0(spk_A_V_q0)
);

spk_packet_rx_spk_A_V #(
    .DataWidth( 128 ),
    .AddressRange( 3040 ),
    .AddressWidth( 12 ))
spk_B_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(spk_B_V_address0),
    .ce0(spk_B_V_ce0),
    .we0(spk_B_V_we0),
    .d0(spk_B_V_d0),
    .q0(spk_B_V_q0)
);

spk_packet_rx_mul_12ns_6ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 13 ))
spk_packet_rx_mul_12ns_6ns_13_3_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_272_p0),
    .din1(grp_fu_272_p1),
    .ce(1'b1),
    .dout(grp_fu_272_p2)
);

spk_packet_rx_mac_muladd_12ns_6ns_5ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
spk_packet_rx_mac_muladd_12ns_6ns_5ns_13_3_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_394_p0),
    .din1(grp_fu_394_p1),
    .din2(grp_fu_394_p2),
    .ce(1'b1),
    .dout(grp_fu_394_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b0 == exitcond1_fu_362_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & (1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & (1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & (1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b0 == exitcond_fu_388_p2))) begin
            ap_reg_ppiten_pp1_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & ~(1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp1_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_reg_ppiten_pp1_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & ~(1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp1_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & ~(1'b0 == tmp_dest_V_1_reg_475))) begin
            ap_reg_ppiten_pp1_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_data_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        post_in_V_data_V_0_has_vld_data_reg <= post_in_V_data_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_data_V_0_in_rdy <= 1'b0;
    end else begin
        post_in_V_data_V_0_in_rdy <= (post_in_V_data_V_0_ack_out | ~post_in_V_data_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_dest_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        post_in_V_dest_V_0_has_vld_data_reg <= post_in_V_dest_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_dest_V_0_in_rdy <= 1'b0;
    end else begin
        post_in_V_dest_V_0_in_rdy <= (post_in_V_dest_V_0_ack_out | ~post_in_V_dest_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_id_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        post_in_V_id_V_0_has_vld_data_reg <= post_in_V_id_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_id_V_0_in_rdy <= 1'b0;
    end else begin
        post_in_V_id_V_0_in_rdy <= (post_in_V_id_V_0_ack_out | ~post_in_V_id_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_last_0_has_vld_data_reg <= 1'b0;
    end else begin
        post_in_V_last_0_has_vld_data_reg <= post_in_V_last_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_last_0_in_rdy <= 1'b0;
    end else begin
        post_in_V_last_0_in_rdy <= (post_in_V_last_0_ack_out | ~post_in_V_last_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_user_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        post_in_V_user_V_0_has_vld_data_reg <= post_in_V_user_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        post_in_V_user_V_0_in_rdy <= 1'b0;
    end else begin
        post_in_V_user_V_0_in_rdy <= (post_in_V_user_V_0_ack_out | ~post_in_V_user_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_data_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        pre_in_V_data_V_0_has_vld_data_reg <= pre_in_V_data_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_data_V_0_in_rdy <= 1'b0;
    end else begin
        pre_in_V_data_V_0_in_rdy <= (pre_in_V_data_V_0_ack_out | ~pre_in_V_data_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_dest_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        pre_in_V_dest_V_0_has_vld_data_reg <= pre_in_V_dest_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_dest_V_0_in_rdy <= 1'b0;
    end else begin
        pre_in_V_dest_V_0_in_rdy <= (pre_in_V_dest_V_0_ack_out | ~pre_in_V_dest_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_id_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        pre_in_V_id_V_0_has_vld_data_reg <= pre_in_V_id_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_id_V_0_in_rdy <= 1'b0;
    end else begin
        pre_in_V_id_V_0_in_rdy <= (pre_in_V_id_V_0_ack_out | ~pre_in_V_id_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_last_0_has_vld_data_reg <= 1'b0;
    end else begin
        pre_in_V_last_0_has_vld_data_reg <= pre_in_V_last_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_last_0_in_rdy <= 1'b0;
    end else begin
        pre_in_V_last_0_in_rdy <= (pre_in_V_last_0_ack_out | ~pre_in_V_last_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_user_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        pre_in_V_user_V_0_has_vld_data_reg <= pre_in_V_user_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pre_in_V_user_V_0_in_rdy <= 1'b0;
    end else begin
        pre_in_V_user_V_0_in_rdy <= (pre_in_V_user_V_0_ack_out | ~pre_in_V_user_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        spk_out_stream_V_data_V_1_mVld <= 1'b0;
    end else begin
        if ((1'b1 == spk_out_stream_V_data_V_1_vld_in)) begin
            spk_out_stream_V_data_V_1_mVld <= 1'b1;
        end else if ((1'b1 == spk_out_stream_V_data_V_1_ack_out)) begin
            spk_out_stream_V_data_V_1_mVld <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        time_stamp_V_0_has_vld_data_reg <= 1'b0;
    end else begin
        time_stamp_V_0_has_vld_data_reg <= time_stamp_V_0_has_vld_data_reg_i;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        time_stamp_V_0_in_rdy <= 1'b0;
    end else begin
        time_stamp_V_0_in_rdy <= (time_stamp_V_0_ack_out | ~time_stamp_V_0_has_vld_data_reg_i);
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & (1'b0 == tmp_dest_V_1_reg_475))) begin
        j3_reg_221 <= ap_const_lv5_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & (1'b0 == exitcond1_reg_503))) begin
        j3_reg_221 <= j_2_reg_498;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & ~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & ~(1'b0 == tmp_dest_V_1_reg_475))) begin
        j_reg_232 <= ap_const_lv5_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it1) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & (1'b0 == exitcond_reg_522))) begin
        j_reg_232 <= j_1_reg_517;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        empty_4_reg_445_0 <= post_in_V_user_V_0_data_out;
        empty_4_reg_445_1 <= post_in_V_last_0_data_out;
        empty_4_reg_445_2 <= post_in_V_id_V_0_data_out;
        empty_4_reg_445_3 <= post_in_V_data_V_0_data_out;
        empty_4_reg_445_4 <= post_in_V_dest_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        empty_reg_407_0 <= pre_in_V_user_V_0_data_out;
        empty_reg_407_2 <= pre_in_V_id_V_0_data_out;
        empty_reg_407_3 <= pre_in_V_data_V_0_data_out;
        empty_reg_407_4 <= pre_in_V_dest_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
        exitcond1_reg_503 <= exitcond1_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
        exitcond_reg_522 <= exitcond_fu_388_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
        j_1_reg_517 <= j_1_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))))) begin
        j_2_reg_498 <= j_2_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        post_in_V_data_V_0_areset_d <= ap_rst_n_inv;
        post_in_V_dest_V_0_areset_d <= ap_rst_n_inv;
        post_in_V_id_V_0_areset_d <= ap_rst_n_inv;
        post_in_V_last_0_areset_d <= ap_rst_n_inv;
        post_in_V_user_V_0_areset_d <= ap_rst_n_inv;
        pre_in_V_data_V_0_areset_d <= ap_rst_n_inv;
        pre_in_V_dest_V_0_areset_d <= ap_rst_n_inv;
        pre_in_V_id_V_0_areset_d <= ap_rst_n_inv;
        pre_in_V_last_0_areset_d <= ap_rst_n_inv;
        pre_in_V_user_V_0_areset_d <= ap_rst_n_inv;
        spk_out_stream_V_data_V_1_areset_d <= ap_rst_n_inv;
        time_stamp_V_0_areset_d <= ap_rst_n_inv;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == post_in_V_data_V_0_vld_in) & (1'b1 == post_in_V_data_V_0_in_rdy))) begin
        post_in_V_data_V_0_data_reg <= post_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == post_in_V_dest_V_0_vld_in) & (1'b1 == post_in_V_dest_V_0_in_rdy))) begin
        post_in_V_dest_V_0_data_reg <= post_in_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == post_in_V_id_V_0_vld_in) & (1'b1 == post_in_V_id_V_0_in_rdy))) begin
        post_in_V_id_V_0_data_reg <= post_in_TID;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == post_in_V_last_0_vld_in) & (1'b1 == post_in_V_last_0_in_rdy))) begin
        post_in_V_last_0_data_reg <= post_in_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == post_in_V_user_V_0_vld_in) & (1'b1 == post_in_V_user_V_0_in_rdy))) begin
        post_in_V_user_V_0_data_reg <= post_in_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == pre_in_V_data_V_0_vld_in) & (1'b1 == pre_in_V_data_V_0_in_rdy))) begin
        pre_in_V_data_V_0_data_reg <= pre_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == pre_in_V_dest_V_0_vld_in) & (1'b1 == pre_in_V_dest_V_0_in_rdy))) begin
        pre_in_V_dest_V_0_data_reg <= pre_in_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == pre_in_V_id_V_0_vld_in) & (1'b1 == pre_in_V_id_V_0_in_rdy))) begin
        pre_in_V_id_V_0_data_reg <= pre_in_TID;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == pre_in_V_user_V_0_vld_in) & (1'b1 == pre_in_V_user_V_0_in_rdy))) begin
        pre_in_V_user_V_0_data_reg <= pre_in_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == spk_out_stream_V_data_V_1_vld_in) & (1'b1 == spk_out_stream_V_data_V_1_sRdy))) begin
        spk_out_stream_V_data_V_1_data_reg <= spk_out_stream_V_data_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == time_stamp_V_0_vld_in) & (1'b1 == time_stamp_V_0_in_rdy))) begin
        time_stamp_V_0_data_reg <= time_stamp_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(1'b0 == empty_4_reg_445_1) & ~ap_sig_618)) begin
        tmp_2_reg_479 <= time_stamp_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        tmp_5_cast_reg_435 <= tmp_5_cast_fu_262_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        tmp_6_reg_464 <= grp_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        tmp_data_V_reg_420 <= empty_reg_407_3;
        tmp_dest_V_reg_426 <= empty_reg_407_4;
        tmp_user_V_reg_415 <= empty_reg_407_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_618)) begin
        tmp_dest_V_1_reg_475 <= empty_4_reg_445_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        tmp_id_V_1_reg_454 <= empty_4_reg_445_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_536)) begin
        tmp_reg_403 <= grp_nbreadreq_fu_90_p7;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st20_fsm_15) & ~(spk_out_stream_V_data_V_1_ack_in == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st20_fsm_15) & ~(spk_out_stream_V_data_V_1_ack_in == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_502) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_518) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_613) begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_471) begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_483) begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_494) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_33) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_900) begin
        ap_sig_cseq_ST_st20_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_446) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_559) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_574) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_695) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_459) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_602) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond1_reg_503))) begin
        j3_phi_fu_225_p4 = j_2_reg_498;
    end else begin
        j3_phi_fu_225_p4 = j3_reg_221;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == exitcond_reg_522))) begin
        j_phi_fu_236_p4 = j_1_reg_517;
    end else begin
        j_phi_fu_236_p4 = j_reg_232;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7))) begin
        post_in_TDATA_blk_n = post_in_V_data_V_0_vld_out;
    end else begin
        post_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        post_in_V_data_V_0_ack_out = 1'b1;
    end else begin
        post_in_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == post_in_V_data_V_0_has_vld_data_reg)) begin
        post_in_V_data_V_0_data_out = post_in_V_data_V_0_data_reg;
    end else begin
        post_in_V_data_V_0_data_out = post_in_TDATA;
    end
end

always @ (*) begin
    if (((1'b1 == post_in_V_data_V_0_vld_in) & (1'b0 == post_in_V_data_V_0_ack_out) & (1'b1 == post_in_V_data_V_0_in_rdy))) begin
        post_in_V_data_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == post_in_V_data_V_0_ack_out) & (1'b1 == post_in_V_data_V_0_has_vld_data_reg) & ((1'b0 == post_in_V_data_V_0_vld_in) | (1'b0 == post_in_V_data_V_0_in_rdy)))) begin
        post_in_V_data_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        post_in_V_data_V_0_has_vld_data_reg_i = post_in_V_data_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        post_in_V_dest_V_0_ack_out = 1'b1;
    end else begin
        post_in_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == post_in_V_dest_V_0_has_vld_data_reg)) begin
        post_in_V_dest_V_0_data_out = post_in_V_dest_V_0_data_reg;
    end else begin
        post_in_V_dest_V_0_data_out = post_in_TDEST;
    end
end

always @ (*) begin
    if (((1'b1 == post_in_V_dest_V_0_vld_in) & (1'b0 == post_in_V_dest_V_0_ack_out) & (1'b1 == post_in_V_dest_V_0_in_rdy))) begin
        post_in_V_dest_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == post_in_V_dest_V_0_ack_out) & (1'b1 == post_in_V_dest_V_0_has_vld_data_reg) & ((1'b0 == post_in_V_dest_V_0_vld_in) | (1'b0 == post_in_V_dest_V_0_in_rdy)))) begin
        post_in_V_dest_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        post_in_V_dest_V_0_has_vld_data_reg_i = post_in_V_dest_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        post_in_V_id_V_0_ack_out = 1'b1;
    end else begin
        post_in_V_id_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == post_in_V_id_V_0_has_vld_data_reg)) begin
        post_in_V_id_V_0_data_out = post_in_V_id_V_0_data_reg;
    end else begin
        post_in_V_id_V_0_data_out = post_in_TID;
    end
end

always @ (*) begin
    if (((1'b1 == post_in_V_id_V_0_vld_in) & (1'b0 == post_in_V_id_V_0_ack_out) & (1'b1 == post_in_V_id_V_0_in_rdy))) begin
        post_in_V_id_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == post_in_V_id_V_0_ack_out) & (1'b1 == post_in_V_id_V_0_has_vld_data_reg) & ((1'b0 == post_in_V_id_V_0_vld_in) | (1'b0 == post_in_V_id_V_0_in_rdy)))) begin
        post_in_V_id_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        post_in_V_id_V_0_has_vld_data_reg_i = post_in_V_id_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        post_in_V_last_0_ack_out = 1'b1;
    end else begin
        post_in_V_last_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == post_in_V_last_0_has_vld_data_reg)) begin
        post_in_V_last_0_data_out = post_in_V_last_0_data_reg;
    end else begin
        post_in_V_last_0_data_out = post_in_TLAST;
    end
end

always @ (*) begin
    if (((1'b1 == post_in_V_last_0_vld_in) & (1'b0 == post_in_V_last_0_ack_out) & (1'b1 == post_in_V_last_0_in_rdy))) begin
        post_in_V_last_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == post_in_V_last_0_ack_out) & (1'b1 == post_in_V_last_0_has_vld_data_reg) & ((1'b0 == post_in_V_last_0_vld_in) | (1'b0 == post_in_V_last_0_in_rdy)))) begin
        post_in_V_last_0_has_vld_data_reg_i = 1'b0;
    end else begin
        post_in_V_last_0_has_vld_data_reg_i = post_in_V_last_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & ~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
        post_in_V_user_V_0_ack_out = 1'b1;
    end else begin
        post_in_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == post_in_V_user_V_0_has_vld_data_reg)) begin
        post_in_V_user_V_0_data_out = post_in_V_user_V_0_data_reg;
    end else begin
        post_in_V_user_V_0_data_out = post_in_TUSER;
    end
end

always @ (*) begin
    if (((1'b1 == post_in_V_user_V_0_vld_in) & (1'b0 == post_in_V_user_V_0_ack_out) & (1'b1 == post_in_V_user_V_0_in_rdy))) begin
        post_in_V_user_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == post_in_V_user_V_0_ack_out) & (1'b1 == post_in_V_user_V_0_has_vld_data_reg) & ((1'b0 == post_in_V_user_V_0_vld_in) | (1'b0 == post_in_V_user_V_0_in_rdy)))) begin
        post_in_V_user_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        post_in_V_user_V_0_has_vld_data_reg_i = post_in_V_user_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0))) begin
        pre_in_TDATA_blk_n = pre_in_V_data_V_0_vld_out;
    end else begin
        pre_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        pre_in_V_data_V_0_ack_out = 1'b1;
    end else begin
        pre_in_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == pre_in_V_data_V_0_has_vld_data_reg)) begin
        pre_in_V_data_V_0_data_out = pre_in_V_data_V_0_data_reg;
    end else begin
        pre_in_V_data_V_0_data_out = pre_in_TDATA;
    end
end

always @ (*) begin
    if (((1'b1 == pre_in_V_data_V_0_vld_in) & (1'b0 == pre_in_V_data_V_0_ack_out) & (1'b1 == pre_in_V_data_V_0_in_rdy))) begin
        pre_in_V_data_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == pre_in_V_data_V_0_ack_out) & (1'b1 == pre_in_V_data_V_0_has_vld_data_reg) & ((1'b0 == pre_in_V_data_V_0_vld_in) | (1'b0 == pre_in_V_data_V_0_in_rdy)))) begin
        pre_in_V_data_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        pre_in_V_data_V_0_has_vld_data_reg_i = pre_in_V_data_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        pre_in_V_dest_V_0_ack_out = 1'b1;
    end else begin
        pre_in_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == pre_in_V_dest_V_0_has_vld_data_reg)) begin
        pre_in_V_dest_V_0_data_out = pre_in_V_dest_V_0_data_reg;
    end else begin
        pre_in_V_dest_V_0_data_out = pre_in_TDEST;
    end
end

always @ (*) begin
    if (((1'b1 == pre_in_V_dest_V_0_vld_in) & (1'b0 == pre_in_V_dest_V_0_ack_out) & (1'b1 == pre_in_V_dest_V_0_in_rdy))) begin
        pre_in_V_dest_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == pre_in_V_dest_V_0_ack_out) & (1'b1 == pre_in_V_dest_V_0_has_vld_data_reg) & ((1'b0 == pre_in_V_dest_V_0_vld_in) | (1'b0 == pre_in_V_dest_V_0_in_rdy)))) begin
        pre_in_V_dest_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        pre_in_V_dest_V_0_has_vld_data_reg_i = pre_in_V_dest_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        pre_in_V_id_V_0_ack_out = 1'b1;
    end else begin
        pre_in_V_id_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == pre_in_V_id_V_0_has_vld_data_reg)) begin
        pre_in_V_id_V_0_data_out = pre_in_V_id_V_0_data_reg;
    end else begin
        pre_in_V_id_V_0_data_out = pre_in_TID;
    end
end

always @ (*) begin
    if (((1'b1 == pre_in_V_id_V_0_vld_in) & (1'b0 == pre_in_V_id_V_0_ack_out) & (1'b1 == pre_in_V_id_V_0_in_rdy))) begin
        pre_in_V_id_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == pre_in_V_id_V_0_ack_out) & (1'b1 == pre_in_V_id_V_0_has_vld_data_reg) & ((1'b0 == pre_in_V_id_V_0_vld_in) | (1'b0 == pre_in_V_id_V_0_in_rdy)))) begin
        pre_in_V_id_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        pre_in_V_id_V_0_has_vld_data_reg_i = pre_in_V_id_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        pre_in_V_last_0_ack_out = 1'b1;
    end else begin
        pre_in_V_last_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == pre_in_V_last_0_vld_in) & (1'b0 == pre_in_V_last_0_ack_out) & (1'b1 == pre_in_V_last_0_in_rdy))) begin
        pre_in_V_last_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == pre_in_V_last_0_ack_out) & (1'b1 == pre_in_V_last_0_has_vld_data_reg) & ((1'b0 == pre_in_V_last_0_vld_in) | (1'b0 == pre_in_V_last_0_in_rdy)))) begin
        pre_in_V_last_0_has_vld_data_reg_i = 1'b0;
    end else begin
        pre_in_V_last_0_has_vld_data_reg_i = pre_in_V_last_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
        pre_in_V_user_V_0_ack_out = 1'b1;
    end else begin
        pre_in_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == pre_in_V_user_V_0_has_vld_data_reg)) begin
        pre_in_V_user_V_0_data_out = pre_in_V_user_V_0_data_reg;
    end else begin
        pre_in_V_user_V_0_data_out = pre_in_TUSER;
    end
end

always @ (*) begin
    if (((1'b1 == pre_in_V_user_V_0_vld_in) & (1'b0 == pre_in_V_user_V_0_ack_out) & (1'b1 == pre_in_V_user_V_0_in_rdy))) begin
        pre_in_V_user_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == pre_in_V_user_V_0_ack_out) & (1'b1 == pre_in_V_user_V_0_has_vld_data_reg) & ((1'b0 == pre_in_V_user_V_0_vld_in) | (1'b0 == pre_in_V_user_V_0_in_rdy)))) begin
        pre_in_V_user_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        pre_in_V_user_V_0_has_vld_data_reg_i = pre_in_V_user_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        spk_A_V_address0 = tmp_12_cast_fu_301_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        spk_A_V_address0 = tmp_5_cast_reg_435;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        spk_A_V_address0 = tmp_16_cast_fu_351_p1;
    end else begin
        spk_A_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_618) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        spk_A_V_ce0 = 1'b1;
    end else begin
        spk_A_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        spk_A_V_d0 = empty_4_reg_445_3;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        spk_A_V_d0 = tmp_data_V_reg_420;
    end else begin
        spk_A_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == tmp_reg_403) & (1'b0 == tmp_dest_V_reg_426)) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_618 & (1'b0 == tmp_dest_V_1_fu_289_p1)))) begin
        spk_A_V_we0 = 1'b1;
    end else begin
        spk_A_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        spk_B_V_address0 = tmp_12_cast_fu_301_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        spk_B_V_address0 = tmp_5_cast_reg_435;
    end else if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it0))) begin
        spk_B_V_address0 = tmp_14_cast_fu_377_p1;
    end else begin
        spk_B_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_618) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it0) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        spk_B_V_ce0 = 1'b1;
    end else begin
        spk_B_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        spk_B_V_d0 = empty_4_reg_445_3;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        spk_B_V_d0 = tmp_data_V_reg_420;
    end else begin
        spk_B_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == tmp_reg_403) & ~(1'b0 == tmp_dest_V_reg_426)) | ((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_618 & ~(1'b0 == tmp_dest_V_1_fu_289_p1)))) begin
        spk_B_V_we0 = 1'b1;
    end else begin
        spk_B_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it1))) begin
        spk_out_stream_V_data_V_1_data_in = spk_B_V_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        spk_out_stream_V_data_V_1_data_in = spk_A_V_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st12_fsm_11) & ~(1'b0 == icmp_fu_322_p2))) begin
        spk_out_stream_V_data_V_1_data_in = tmp_data_V_5_fu_331_p4;
    end else begin
        spk_out_stream_V_data_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st12_fsm_11) & ~(1'b0 == icmp_fu_322_p2) & ~(~(1'b0 == icmp_fu_322_p2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it1) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))))) begin
        spk_out_stream_V_data_V_1_vld_in = 1'b1;
    end else begin
        spk_out_stream_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st12_fsm_11) & ~(1'b0 == icmp_fu_322_p2)) | (1'b1 == ap_sig_cseq_ST_st13_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_13) & (1'b1 == ap_reg_ppiten_pp0_it1)) | (1'b1 == ap_reg_ppiten_pp0_it2) | ((1'b1 == ap_sig_cseq_ST_pp1_stg0_fsm_14) & (1'b1 == ap_reg_ppiten_pp1_it1)) | (1'b1 == ap_reg_ppiten_pp1_it2))) begin
        spk_out_stream_V_data_V_TDATA_blk_n = spk_out_stream_V_data_V_1_sRdy;
    end else begin
        spk_out_stream_V_data_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(1'b0 == empty_4_reg_445_1) & ~ap_sig_618)) begin
        time_stamp_V_0_ack_out = 1'b1;
    end else begin
        time_stamp_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == time_stamp_V_0_has_vld_data_reg)) begin
        time_stamp_V_0_data_out = time_stamp_V_0_data_reg;
    end else begin
        time_stamp_V_0_data_out = time_stamp_V_TDATA;
    end
end

always @ (*) begin
    if (((1'b1 == time_stamp_V_0_vld_in) & (1'b0 == time_stamp_V_0_ack_out) & (1'b1 == time_stamp_V_0_in_rdy))) begin
        time_stamp_V_0_has_vld_data_reg_i = 1'b1;
    end else if (((1'b1 == time_stamp_V_0_ack_out) & (1'b1 == time_stamp_V_0_has_vld_data_reg) & ((1'b0 == time_stamp_V_0_vld_in) | (1'b0 == time_stamp_V_0_in_rdy)))) begin
        time_stamp_V_0_has_vld_data_reg_i = 1'b0;
    end else begin
        time_stamp_V_0_has_vld_data_reg_i = time_stamp_V_0_has_vld_data_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st11_fsm_10) & ~(1'b0 == empty_4_reg_445_1))) begin
        time_stamp_V_TDATA_blk_n = time_stamp_V_0_vld_out;
    end else begin
        time_stamp_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (((grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else if ((~(grp_nbreadreq_fu_90_p7 == 1'b0) & ~ap_sig_536)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : begin
            if (((1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end else if ((~(1'b0 == grp_nbreadreq_fu_120_p7) & ~ap_sig_579)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            if (((1'b0 == empty_4_reg_445_1) & ~ap_sig_618)) begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end else if ((~(1'b0 == empty_4_reg_445_1) & ~ap_sig_618)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st12_fsm_11 : begin
            if (((1'b0 == icmp_fu_322_p2) & ~(~(1'b0 == icmp_fu_322_p2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end else if ((~(1'b0 == icmp_fu_322_p2) & ~(~(1'b0 == icmp_fu_322_p2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)))) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        end
        ap_ST_st13_fsm_12 : begin
            if ((~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & ~(1'b0 == tmp_dest_V_1_reg_475))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_14;
            end else if ((~(1'b0 == spk_out_stream_V_data_V_1_ack_in) & (1'b0 == tmp_dest_V_1_reg_475))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        end
        ap_ST_pp0_stg0_fsm_13 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_13;
            end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_13;
            end
        end
        ap_ST_pp1_stg0_fsm_14 : begin
            if (~((1'b1 == ap_reg_ppiten_pp1_it2) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b1 == ap_reg_ppiten_pp1_it1))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_14;
            end else if (((1'b1 == ap_reg_ppiten_pp1_it2) & ~(((1'b1 == ap_reg_ppiten_pp1_it1) & (1'b0 == spk_out_stream_V_data_V_1_ack_in)) | ((1'b1 == ap_reg_ppiten_pp1_it2) & (1'b0 == spk_out_stream_V_data_V_1_ack_in))) & ~(1'b1 == ap_reg_ppiten_pp1_it1))) begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_14;
            end
        end
        ap_ST_st20_fsm_15 : begin
            if (~(spk_out_stream_V_data_V_1_ack_in == 1'b0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_33 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_446 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_459 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_471 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_483 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_494 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_502 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_518 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_536 = (~(grp_nbreadreq_fu_90_p7 == 1'b0) & (pre_in_V_user_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_sig_559 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_574 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_579 = (~(1'b0 == grp_nbreadreq_fu_120_p7) & (post_in_V_user_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_sig_602 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_613 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_618 = (~(1'b0 == empty_4_reg_445_1) & (time_stamp_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_sig_695 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_900 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

assign exitcond1_fu_362_p2 = ((j3_phi_fu_225_p4 == ap_const_lv5_12) ? 1'b1 : 1'b0);

assign exitcond_fu_388_p2 = ((j_phi_fu_236_p4 == ap_const_lv5_12) ? 1'b1 : 1'b0);

assign grp_fu_272_p0 = grp_fu_272_p00;

assign grp_fu_272_p00 = empty_4_reg_445_2;

assign grp_fu_272_p1 = ap_const_lv13_13;

assign grp_fu_394_p0 = grp_fu_394_p00;

assign grp_fu_394_p00 = empty_reg_407_2;

assign grp_fu_394_p1 = ap_const_lv13_13;

assign grp_fu_394_p2 = grp_fu_394_p20;

assign grp_fu_394_p20 = tmp_user_V_reg_415;

assign grp_nbreadreq_fu_120_p7 = (post_in_V_user_V_0_vld_out & post_in_V_last_0_vld_out & post_in_V_id_V_0_vld_out & post_in_V_data_V_0_vld_out & post_in_V_dest_V_0_vld_out);

assign grp_nbreadreq_fu_90_p7 = (pre_in_V_user_V_0_vld_out & pre_in_V_last_0_vld_out & pre_in_V_id_V_0_vld_out & pre_in_V_data_V_0_vld_out & pre_in_V_dest_V_0_vld_out);

assign icmp_fu_322_p2 = (($signed(tmp_3_fu_312_p4) > $signed(29'b00000000000000000000000000000)) ? 1'b1 : 1'b0);

assign j_1_fu_382_p2 = (j_phi_fu_236_p4 + ap_const_lv5_1);

assign j_2_fu_356_p2 = (j3_phi_fu_225_p4 + ap_const_lv5_1);

assign loc_V_5_trunc_fu_328_p1 = tmp_id_V_1_reg_454;

assign post_in_TREADY = post_in_V_dest_V_0_in_rdy;

assign post_in_V_data_V_0_vld_in = post_in_TVALID;

assign post_in_V_data_V_0_vld_out = ((post_in_TVALID | post_in_V_data_V_0_has_vld_data_reg) & ~post_in_V_data_V_0_areset_d);

assign post_in_V_dest_V_0_vld_in = post_in_TVALID;

assign post_in_V_dest_V_0_vld_out = ((post_in_TVALID | post_in_V_dest_V_0_has_vld_data_reg) & ~post_in_V_dest_V_0_areset_d);

assign post_in_V_id_V_0_vld_in = post_in_TVALID;

assign post_in_V_id_V_0_vld_out = ((post_in_TVALID | post_in_V_id_V_0_has_vld_data_reg) & ~post_in_V_id_V_0_areset_d);

assign post_in_V_last_0_vld_in = post_in_TVALID;

assign post_in_V_last_0_vld_out = ((post_in_TVALID | post_in_V_last_0_has_vld_data_reg) & ~post_in_V_last_0_areset_d);

assign post_in_V_user_V_0_vld_in = post_in_TVALID;

assign post_in_V_user_V_0_vld_out = ((post_in_TVALID | post_in_V_user_V_0_has_vld_data_reg) & ~post_in_V_user_V_0_areset_d);

assign pre_in_TREADY = pre_in_V_dest_V_0_in_rdy;

assign pre_in_V_data_V_0_vld_in = pre_in_TVALID;

assign pre_in_V_data_V_0_vld_out = ((pre_in_TVALID | pre_in_V_data_V_0_has_vld_data_reg) & ~pre_in_V_data_V_0_areset_d);

assign pre_in_V_dest_V_0_vld_in = pre_in_TVALID;

assign pre_in_V_dest_V_0_vld_out = ((pre_in_TVALID | pre_in_V_dest_V_0_has_vld_data_reg) & ~pre_in_V_dest_V_0_areset_d);

assign pre_in_V_id_V_0_vld_in = pre_in_TVALID;

assign pre_in_V_id_V_0_vld_out = ((pre_in_TVALID | pre_in_V_id_V_0_has_vld_data_reg) & ~pre_in_V_id_V_0_areset_d);

assign pre_in_V_last_0_vld_in = pre_in_TVALID;

assign pre_in_V_last_0_vld_out = ((pre_in_TVALID | pre_in_V_last_0_has_vld_data_reg) & ~pre_in_V_last_0_areset_d);

assign pre_in_V_user_V_0_vld_in = pre_in_TVALID;

assign pre_in_V_user_V_0_vld_out = ((pre_in_TVALID | pre_in_V_user_V_0_has_vld_data_reg) & ~pre_in_V_user_V_0_areset_d);

always @ (*) begin
    spk_out_stream_V_data_V_1_ack_in = (~spk_out_stream_V_data_V_1_areset_d & (spk_out_stream_V_data_V_TREADY | ~spk_out_stream_V_data_V_1_mVld));
end

assign spk_out_stream_V_data_V_1_ack_out = spk_out_stream_V_data_V_TREADY;

always @ (*) begin
    spk_out_stream_V_data_V_1_sRdy = (~spk_out_stream_V_data_V_1_areset_d & (spk_out_stream_V_data_V_TREADY | ~spk_out_stream_V_data_V_1_mVld));
end

assign spk_out_stream_V_data_V_TDATA = spk_out_stream_V_data_V_1_data_reg;

assign spk_out_stream_V_data_V_TVALID = spk_out_stream_V_data_V_1_mVld;

assign t_fu_307_p2 = ($signed(tmp_2_reg_479) + $signed(ap_const_lv32_FFFFFFFF));

assign time_stamp_V_0_vld_in = time_stamp_V_TVALID;

assign time_stamp_V_0_vld_out = ((time_stamp_V_TVALID | time_stamp_V_0_has_vld_data_reg) & ~time_stamp_V_0_areset_d);

assign time_stamp_V_TREADY = time_stamp_V_0_in_rdy;

assign tmp_10_fu_346_p2 = (tmp_6_reg_464 + tmp_13_cast_fu_342_p1);

assign tmp_11_cast_fu_368_p1 = j_phi_fu_236_p4;

assign tmp_12_cast_fu_301_p1 = $signed(tmp_s_fu_296_p2);

assign tmp_13_cast_fu_342_p1 = j3_phi_fu_225_p4;

assign tmp_14_cast_fu_377_p1 = $signed(tmp_8_fu_372_p2);

assign tmp_16_cast_fu_351_p1 = $signed(tmp_10_fu_346_p2);

assign tmp_3_fu_312_p4 = {{t_fu_307_p2[ap_const_lv32_1F : ap_const_lv32_3]}};

assign tmp_5_cast_fu_262_p1 = $signed(grp_fu_394_p3);

assign tmp_8_cast_fu_292_p1 = empty_4_reg_445_0;

assign tmp_8_fu_372_p2 = (tmp_6_reg_464 + tmp_11_cast_fu_368_p1);

assign tmp_data_V_5_fu_331_p4 = {{{{ap_const_lv64_0}, {t_fu_307_p2}}}, {loc_V_5_trunc_fu_328_p1}};

assign tmp_dest_V_1_fu_289_p1 = empty_4_reg_445_4;

assign tmp_s_fu_296_p2 = (tmp_6_reg_464 + tmp_8_cast_fu_292_p1);

endmodule //spk_packet_rx
