-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity syncGen_time_to_sync_rom is 
    generic(
             dwidth     : integer := 11; 
             awidth     : integer := 6; 
             mem_size    : integer := 42
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of syncGen_time_to_sync_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "00000000000", 1 => "00000000001", 2 => "00000000011", 
    3 => "00001000000", 4 => "00001101001", 5 => "00010110101", 
    6 => "00100001010", 7 => "00100011100", 8 => "00101111110", 
    9 => "00111010101", 10 => "01000010011", 11 => "01000100001", 
    12 => "01000100111", 13 => "01001100110", 14 => "01011001000", 
    15 => "01011010110", 16 => "01100101010", 17 => "01100111110", 
    18 => "01101001110", 19 => "01101111101", 20 => "01111010111", 
    21 => "10000000000", 22 => "10001011001", 23 => "10010101100", 
    24 => "10010111110", 25 => "10011011010", 26 => "10011101001", 
    27 => "10100000101", 28 => "10101100011", 29 => "10111000101", 
    30 => "11000000001", 31 => "11000011111", 32 => "11001100010", 
    33 => "11010100001", 34 => "11010110110", 35 => "11011010000", 
    36 => "11011010101", 37 => "11100010011", 38 => "11101000110", 
    39 => "11101111101", 40 => "11111001011", 41 => "11111111111" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity syncGen_time_to_sync is
    generic (
        DataWidth : INTEGER := 11;
        AddressRange : INTEGER := 42;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of syncGen_time_to_sync is
    component syncGen_time_to_sync_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    syncGen_time_to_sync_rom_U :  component syncGen_time_to_sync_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


